server:
  port: 9999
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/JobPortel?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
     show-sql: true

     properties:
       hibernate:
           dialect: org.hibernate.dialect.MySQL8Dialect

           ddl-auto: update

  #mvc:
   # view:
     # prefix: /view/
    #  suffix: .jsp
      
 # app1:
     # messages:
      # saveSuccess: Contact save Succesfully
       #saveFail: Contact Failed To Save  


    
